# Controls when the workflow will run
name: On Pull Request

# Workflow syntax https://bit.ly/46gUFL0
# Dropping the restrictions on pushes entirely means
# triggering on all of them (commits, and also tags):
on:
  push:
  pull_request:
  # branches:
  #   - '**'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test